version: '3.8'

services:
  app:
    build: .
    container_name: tmdb_app
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /usr/src/app
    command: ["bash", "-c", "source activate tmdb_env && python main.py"]
  db:
    image: mysql:8
    container_name: tmdb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: tmdb_movie_analysis
    ports:
      - "3306:3306"