version: '3.8'

services:
  app:
    build: 
      context: .
    volumes:
      - .:/usr/src/app
    container_name: tmdb_app
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    command: ["/bin/bash", "-c", "source activate tmdb_env && python main.py"]
  db:
    image: mysql:8
    container_name: tmdb_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tmdb_movie_analysis
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d